# -*- coding: utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Shortener::ShortenedUrlsController do

  # This should return the minimal set of attributes required to create a valid
  # Shortener::ShortenedUrl. As you add validations to Shortener::ShortenedUrl, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      url: 'http://www.doorkeeperhq.com/'  
    }
  end
  def another_valid_attributes
    {
      url: 'http://www.doorkeeper.jp/'  
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Shortener::ShortenedUrlsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all shortener_shortened_urls as @shortener_shortened_urls" do
      shortened_url = Shortener::ShortenedUrl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shortener_shortened_urls).should include(shortened_url)
    end
  end

  describe "GET show" do
    it "assigns the requested shortener_shortened_url as @shortener_shortened_url" do
      shortened_url = Shortener::ShortenedUrl.create! valid_attributes
      get :show, {:id => shortened_url.to_param}, valid_session
      assigns(:shortener_shortened_url).should eq(shortened_url)
    end
  end

  describe "GET new" do
    it "assigns a new shortener_shortened_url as @shortener_shortened_url" do
      get :new, {}, valid_session
      assigns(:shortener_shortened_url).should be_a_new(Shortener::ShortenedUrl)
    end
  end

  describe "GET edit" do
    it "assigns the requested shortener_shortened_url as @shortener_shortened_url" do
      shortened_url = Shortener::ShortenedUrl.create! valid_attributes
      get :edit, {:id => shortened_url.to_param}, valid_session
      assigns(:shortener_shortened_url).should eq(shortened_url)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      before(:all) do
        DatabaseCleaner.clean
      end

      it "creates a new Shortener::ShortenedUrl" do
        expect {
          post :create, {:shortener_shortened_url => valid_attributes}, valid_session
        }.to change(Shortener::ShortenedUrl, :count).by(1)
      end

      it "won't create new Shortener::ShortenedUrl for same url" do
        expect {
          post :create, {:shortener_shortened_url => valid_attributes}, valid_session
        }.to change(Shortener::ShortenedUrl, :count).by(0)
      end

      it "assigns a newly created shortener_shortened_url as @shortener_shortened_url" do
        post :create, {:shortener_shortened_url => valid_attributes}, valid_session
        assigns(:shortener_shortened_url).should be_a(Shortener::ShortenedUrl)
        assigns(:shortener_shortened_url).should be_persisted
      end

      it "redirects to the created shortener_shortened_url" do
        post :create, {:shortener_shortened_url => valid_attributes}, valid_session
        response.should redirect_to(Shortener::ShortenedUrl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shortener_shortened_url as @shortener_shortened_url" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shortener::ShortenedUrl.any_instance.stub(:save).and_return(false)
        post :create, {:shortener_shortened_url => {  }}, valid_session
        assigns(:shortener_shortened_url).should be_a_new(Shortener::ShortenedUrl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shortener::ShortenedUrl.any_instance.stub(:save).and_return(false)
        post :create, {:shortener_shortened_url => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shortener_shortened_url" do
        shortened_url = Shortener::ShortenedUrl.create! valid_attributes
        # Assuming there are no other shortener_shortened_urls in the database, this
        # specifies that the Shortener::ShortenedUrl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shortener::ShortenedUrl.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => shortened_url.to_param, :shortener_shortened_url => { "these" => "params" }}, valid_session
      end

      it "assigns the requested shortener_shortened_url as @shortener_shortened_url" do
        shortened_url = Shortener::ShortenedUrl.create! valid_attributes
        put :update, {:id => shortened_url.to_param, :shortener_shortened_url => valid_attributes}, valid_session
        assigns(:shortener_shortened_url).should eq(shortened_url)
      end

      it "redirects to the shortener_shortened_url" do
        shortened_url = Shortener::ShortenedUrl.create! valid_attributes
        put :update, {:id => shortened_url.to_param, :shortener_shortened_url => valid_attributes}, valid_session
        response.should redirect_to(shortened_url)
      end
    end

    describe "with invalid params" do
      it "assigns the shortener_shortened_url as @shortener_shortened_url" do
        shortened_url = Shortener::ShortenedUrl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shortener::ShortenedUrl.any_instance.stub(:save).and_return(false)
        put :update, {:id => shortened_url.to_param, :shortener_shortened_url => {  }}, valid_session
        assigns(:shortener_shortened_url).should eq(shortened_url)
      end

      it "re-renders the 'edit' template" do
        shortened_url = Shortener::ShortenedUrl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shortener::ShortenedUrl.any_instance.stub(:save).and_return(false)
        put :update, {:id => shortened_url.to_param, :shortener_shortened_url => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shortener_shortened_url" do
      shortened_url = Shortener::ShortenedUrl.create! valid_attributes
      expect {
        delete :destroy, {:id => shortened_url.to_param}, valid_session
      }.to change(Shortener::ShortenedUrl, :count).by(-1)
    end

    it "redirects to the shortener_shortened_urls list" do
      shortened_url = Shortener::ShortenedUrl.create! valid_attributes
      delete :destroy, {:id => shortened_url.to_param}, valid_session
      response.should redirect_to(shortener_shortened_urls_url)
    end
  end

end
